### ISSUE TITLE
First time using this Client need some assistance

### ISSUE THREAD

**Issue by djtwist** [laserir/NL2Client#1]
So I stubbled upon this client due to my other control panel getting corrupted and the person that coded it is non existent no more.

What I am seeing is when I say, #include <NL2Client.h> I get the following error:

In file included from D:\Documents\NoLimitsCoaster\TCP_Panel_v1\Coaster_Panel_TCP_01\Coaster_Panel_TCP_01.ino:1:0:
d:\Documents\Arduino\libraries\NL2Client\src/NL2Client.h:34:5: error: 'WiFiClient' does not name a type; did you mean 'NL2Client'?
     WiFiClient client;
     ^~~~~~~~~~
     NL2Client
d:\Documents\Arduino\libraries\NL2Client\src/NL2Client.h: In member function 'boolean NL2Client::conn()':
d:\Documents\Arduino\libraries\NL2Client\src/NL2Client.h:49:11: error: 'client' was not declared in this scope
       if(!client.connected()){
           ^~~~~~
d:\Documents\Arduino\libraries\NL2Client\src/NL2Client.h:49:11: note: suggested alternative: 'Print'
       if(!client.connected()){
           ^~~~~~
           Print
In file included from D:\Documents\NoLimitsCoaster\TCP_Panel_v1\Coaster_Panel_TCP_01\Coaster_Panel_TCP_01.ino:1:0:
d:\Documents\Arduino\libraries\NL2Client\src/NL2Client.h: In member function 'boolean NL2Client::sendMessage(unsigned int, uint32_t, short unsigned int, byte*)':
d:\Documents\Arduino\libraries\NL2Client\src/NL2Client.h:67:17: error: 'client' was not declared in this scope
           while(client.available()){client.read();} //Clear receive buffer
                 ^~~~~~
d:\Documents\Arduino\libraries\NL2Client\src/NL2Client.h:67:17: note: suggested alternative: 'Print'
           while(client.available()){client.read();} //Clear receive buffer
                 ^~~~~~
                 Print
d:\Documents\Arduino\libraries\NL2Client\src/NL2Client.h:103:11: error: 'client' was not declared in this scope
           client.write(writeArray,10+datasize);
           ^~~~~~
d:\Documents\Arduino\libraries\NL2Client\src/NL2Client.h:103:11: note: suggested alternative: 'Print'
           client.write(writeArray,10+datasize);
           ^~~~~~
           Print

exit status 1

Compilation error: exit status 1

I also tried using your example code and this plus other errors occur so let's just start with what I mentioned above. I am trying to get my control panel to function again. What I am missing is the actually states from the game to control lights and functions. If anything I can make the Arduino send keyboard commands BUT I would like the station statuses to control the panel code.

Thanks for your time,

Tyson

**Comment by laserir** [comment]
Hi Tyson, what kind of hardware do you use?

**Comment by djtwist** [comment]
I am using a Arduino Leonardo.Would this be board based and your library needs certain board to work? I saw it complaining about the Wifi but in my mind wouldn’t the library take care of it self if even when you have a fresh slate code wise and only #define <NL2Client.h>That is all I have was a striped down code with just that. Plus my test pin for light and button but other than that standard I\O code. Best Regards,TysonOn May 23, 2023, at 6:14 AM, laserir ***@***.***> wrote:﻿
Hi Tyson, what kind of hardware do you use?

**Comment by djtwist** [comment]
If I need to use a different board to use your client which board should I look at?

**Comment by laserir** [comment]
Right, you will need some piece of hardware to connect to the local network to work with the telemetry server. The Leonardo is not capable of WiFi or Ethernet without an additional shield.

I‘d advise to get an ESP32 (like Lolin32) and start off with the sample script. I/O pins and behavior is defined in your code. The library takes care of the telemetry server communication.

Let me know if you need further assistance.

**Comment by djtwist** [comment]
Looks like you can program these with the Arduino IDE as well. I will stop by and pick one up tonight and give it a shot! Thank you.

**Comment by djtwist** [comment]
How do I know if it has connected to NL?

**Comment by laserir** [comment]
Please see the available functions here: https://github.com/laserir/NL2Client#functions

You can use .updateTelemetry() to check if the server returns data (true) or not (false).

As a first step try to get the example running on the ESP32. Be aware that you need to add the board definitions first if using Arduino IDE (see here: https://randomnerdtutorials.com/installing-the-esp32-board-in-arduino-ide-windows-instructions/)

You will need to start NL2 with the server options (see here: https://www.symprojects.com/nolimits2-roller-coaster-simulation-telemetry)

Check for the IP of the computer running NL2 for the instance initialization.

Hope that helps :)

**Comment by djtwist** [comment]
I already had that set up…I have no idea if it is even connected via Wi-Fi or not nor if NL even see it.

map it did not help.

**Comment by laserir** [comment]
Do you use the example code? If so, AutoConnect takes care of the WiFi stuff. You can connect in any way you like depending on the hardware. Just declare a client that will be used for network communication.

could you post your code?

**Comment by djtwist** [comment]
I am using the Inland ESP32 wroom 
Software wise I loaded your example program onto the board. 
beyond that I have not modified the code yet nor have I hooked any buttons/lights into the board yet.
The question here really is how does the bored connect to the computer. Wi-Fi is the first answer but how do you know you are connected. Does this bored act as a device like a router that you connect your computer to over Wi-Fi? And once that connection is done what is the way I know that I am actually connect to the computer it self. 
the next question would be once connected to the computer I would I know that I am actually connected to NL2?

**Comment by laserir** [comment]
The example sketch uses the AutoConnect library. If the upload was successful, connect to the WiFi network it creates, to set your local networks credentials. It must be the same network your NL2 computer is connected to.
Please remember to substitute the IP in the sketch with your NL2 computer’s.

**Comment by djtwist** [comment]
I did all of that and all that happened when I connected the computer to the ESP32 was it opened my web browser and took it to MSN . Com which is not my home page.
Launched the game and nothing seemed to work.

**Comment by laserir** [comment]
Dear Tyson, I really hope we can work this out together, but I think we need to start with some basics.

1. Do you run NL2 via Steam?
2. Which operating system do you use? (Windows, Mac OS...)
3. Is your computer connected to your home network? (WiFi or Ethernet doesn't matter)

**Comment by djtwist** [comment]
1. Non Steam version and telemetry server set up with proper port. Was using it with another control panel but due to that software interference not being updated I am not using it no more BUT everything is still set up for NL2
2. Windows 10
3. Yes hard wired so my Wi-Fi is available on the computer.

**Comment by laserir** [comment]
Okay... So, please check for the IP address of the computer running NL2 (see here: https://support.microsoft.com/en-us/windows/find-your-ip-address-in-windows-f21a9bbc-c582-55cd-35e0-73431160a1b9#Category=Windows_10).

Next, check that line 13 of the example code matches this IP address AND the port of the telemetry server that you set in the command line options for NL2 --> Replace **192.168.178.10** in **NL2Client nl2("192.168.178.10", 15151, 500, false);** and (if necessary) and Replace **15151** with the port.

Recompile and upload the sketch afterwards.

Next, keep your WiFi credentials ready (SSID (the "name" of the network) and password. Connect to the WiFi created by the ESP32, password is **nl2**. Open 192.168.4.1 (or any domain), this will get you to the menu. Enter and save your credentials here.

Most importantly... Open the serial monitor of Arduino IDE. You will see the progress there!

Give it a try!

**Comment by djtwist** [comment]
This step here still does nothing. Unable to "connect to this menu" you talk about.

"Next, keep your WiFi credentials ready (SSID (the "name" of the network) and password. Connect to the WiFi created by the ESP32, password is nl2. Open 192.168.4.1 (or any domain), this will get you to the menu. Enter and save your credentials here.

Most importantly... Open the serial monitor of Arduino IDE. You will see the progress there!"

**Comment by djtwist** [comment]
I really wish you did not use Wifi for this application. Running a USB and talking over the serial connection would have been better. I have no clue how to set that up nor do I have any idea how to get this software to work. Sort of disappointed since no one else has any solution to use a control panel with NL2 any more.

**Comment by laserir** [comment]
Well… NL2 only supports the telemetry data via TCP, hence network is the only option for synchronized behavior. Unless… you could implement a python script to grab the data locally and then convert to serial, but that wouldn’t be any easier I think.
The keyboard-emulator panels you might be referring to have the problem of guessing the state of NL2 and mostlikely would only work under certain conditions.
Sorry you couldn’t figure it out, but for your desired application this library might just not be for you.
