### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by mike00107** [laserir/NL2Client#2]
so i am trying to use the library now. but i am getting an Compilation error: AutoConnect.h: No such file or directory. i have installed the library and i am using the Wemos LOLIN D32 V1 - ESP32 - CH340C. wich i assume is the same one you are using. am i missing an library or is there something else going wrong?

**Comment by mike00107** [comment]
got it to compile. needed the AutoConnect Library.

**Comment by laserir** [comment]
Good 😊 Let me know when you need further assistance.

**Comment by mike00107** [comment]
well maby you can help me with this.

i get this error in the monitor when i use your example code. i have no clue how the autoconnect library works.

`rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13232
load:0x40080400,len:3028
entry 0x400805e4
[  1260][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[  1280][E][WiFiSTA.cpp:317] begin(): connect failed! 0x300a
[  1295][E][WiFiAP.cpp:147] softAP(): passphrase too short!
`

**Comment by mike00107** [comment]
i have managed to connect my pc to the ESP (the preious error is that no connections are active on the ESP

when i look in the monitor now i get this:

[163888][E][WebServer.cpp:648] _handleRequest(): request handler not found

it is being spammed in the monitor.

**Comment by mike00107** [comment]
i have manage to connect the ESP to my local network. now i assume it is working (i have enabled the debug print in your code and its printing this). at the moment of typing this i have not connected any buttons.

0>0
1>1
2>0
3>0
0>0
1>1
2>0
3>0

i am going to continue on thursday

**Comment by laserir** [comment]
Could you please provide the complete serial console output?

**Comment by mike00107** [comment]
Not nearby my pc atm but it is spamming tbe above mentioned in my console. (So a long list of 0>0 1>1 etc). Might look tomorrow. Btw the nl2client ip adres is that my pc’s local ip address or something else?

**Comment by laserir** [comment]
Please connect the ESP, open the serial terminal and reset the board. I‘d need the complete output including the connection messages. It seems as you are indeed connected to your WiFi, but not to the server.

The IP address must match the server (PC that runs NL2).

You will need to start NL2 with the server options (see here: https://www.symprojects.com/nolimits2-roller-coaster-simulation-telemetry)

**Comment by mike00107** [comment]
Thnx for the response. Will check tomorrow. The ip address is correct then. I have nolimits with the telemetry started. And I think your suspissions are correct that I am not connected to the telemetry server.

**Comment by laserir** [comment]
> (i have enabled the debug print in your code and its printing this)

Right, took the time to look into what's going on. What I didn't get at first is, that you uncommented line 205 of the [example sketch](https://github.com/laserir/NL2Client/blob/main/examples/NL2Panel/NL2Panel.ino) 

This means the output
```
0>0 
1>1 
2>0 
3>0 
0>0 
1>1 
2>0 
3>0
```
is just indicating the LED status, it is set by this in the loop():
```
  if(digitalRead(buttonPin[0]) == HIGH){ //Keyswitch OFF
    LEDState[0] = 0;
    LEDState[1] = 1;
    LEDState[2] = 0;
    LEDState[3] = 0;
    delay(50);
    return;
    }
```
Coincidentally you'll notice that buttonPin[0] (13, if not changed) must be pulled to GND to pass on to the nl2 functions., which means until now there was not even a connection attempt (to the server), but also shows that the WiFi connection indeed was successful, as the loop() is entered.

TODOs for you:
- Connect pin 13 to GND (this would be the key switch on the panel)
- Leave line 205 uncommented and look what happens. The output after 0> should either be constantly 1 or alternating between 1 and 0. See line 139 and following to know what LED indicator means what.

**Comment by mike00107** [comment]
hello thank you for your help. i think it is working now! i am getting client connected in NL2. but i am going to test the buttons first. this is how the console looks like now:

`WiFi connected: 192.168.178.18
0>0
1>0
2>0
3>0
0>1
1>0
2>0
3>0
0>1
1>0
2>0
3>0
0>1
1>0
2>0
3>0
0>1
1>0
2>0
3>0
0>1
1>0
2>0
3>0
0>1
1>0
2>0
3>0
0>1
1>0
2>0
3>0
0>1
1>0
2>0
3>0
0>1
1>0
2>0
3>0
0>1
1>0
2>0
3>0
0>1
1>0
2>0
3>0
0>1
1>0
2>0
3>0
0>1
1>0
2>0
3>0
`

but i am sometimes getting Client error! errorcode -1 disconecting on NL2. ill keep you posted

**Comment by mike00107** [comment]
it is working thank you so mutch for your help! i hope other peeps can figure this out with the help of this issue.

pictures of my pannel:

https://imgur.com/a/aa41mVz

**Comment by laserir** [comment]
Wow dude, that looks amazing! Don’t hesitate if you need further assistance, happy to help! :)
